name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Check Flutter & Dart version
        run: flutter --version

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: "DEBUG: show lcov path before and after sed"
        run: |
          echo "ANTES:"
          grep SF coverage/lcov.info | head -n 5
          sed -i 's|SF:lib/|SF:./lib/|g' coverage/lcov.info
          echo "DESPUÉS:"
          grep SF coverage/lcov.info | head -n 5

      - name: Install Python dependencies (lcov2cobertura)
        run: pip install lcov2cobertura

      - name: Convert lcov.info to cobertura.xml (v1 compatible)
        run: lcov_cobertura coverage/lcov.info --output coverage/cobertura.xml

      - name: List converted coverage (verificación)
        run: |
          echo "Contenido de coverage/"
          ls -la coverage
          echo "Primeras 20 líneas de cobertura.xml"
          head -n 20 coverage/cobertura.xml

      - name: Download SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=acevedoossiel_panapan \
            -Dsonar.organization=acevedoossiel \
            -Dsonar.sources=lib \
            -Dsonar.tests=test \
            -Dsonar.coverageReportPaths=coverage/cobertura.xml \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
